### ISSUE TITLE
openVidu - tutorial 

### ISSUE THREAD

**Issue by dongsub-joung** [Minwooooooo/FinalProject#1]
# tutorial test(sample code test)

1. brave

> None, Login func
 
![Screenshot from 2022-09-20 00-00-01](https://user-images.githubusercontent.com/59364300/191049236-09cd9133-8363-407f-879f-6c496fda71ba.png)

2. firefox

> None, video chat func

![Screenshot from 2022-09-19 23-59-10](https://user-images.githubusercontent.com/59364300/191049315-536828c3-5f24-43b3-8a5e-76b841985219.png)

# conclusion 
It is better that progress on the code with a complete understanding of custom handling.

In https://docs.openvidu.io/en/stable/tutorials/openvidu-js-java/
> Understanding the code

**Comment by Minwooooooo** [comment]
Q. 영상 송출은 되나요??
