### ISSUE TITLE
HttpServletRequest request 사용자 아이디 꺼내기

### ISSUE THREAD

**Issue by ss990321** [Minwooooooo/FinalProject#15]
![image](https://user-images.githubusercontent.com/110081578/192498721-ffc9e658-c558-41b0-a8d4-346929770300.png)

HttpServletRequest request으로 토큰을 받아서 사용자 아이디를 어떻게 꺼내오나요??

**Comment by Minwooooooo** [comment]
1. HttpServletRequest에서 토큰 꺼내기  
    - ```String token = JwtTokenProvider.getToken(HttpServletRequest)```

2. 꺼낸 토큰 복호화하기
    - ```Claims claim = JwtTokenProvidr.tempClaim(token)```
    -  주의 : 헤더에서 토큰의 형태는 
    Authorization : Bearer {토큰} 입니다.
    tempClaim은 Bearer 을 제외하고 {토큰}만 substring으로 추출하는 부분이 들어가있어서 일부 순수한 token 만으로 실행시 오류가 발생합니다.
getToken(request)사용시 순수한 토큰만 나옵니다.
따라서
#14 이슈에 명시해놓은 부분 수정 전 까지는
순수토큰 복호화 시 : tempClaimNoBaerer 함수를 사용하시고
Bearer + 토큰 복호화시 : tempClaim함수를 사용하시면 됩니다

3. 복호화된 Claims 에서 Id 꺼내기
  - ```claim.getSubject```

4. 추가 -  Id 이외의 정보 꺼내기
  - 현재 토큰은
```
Jwts.builder()
                .setSubject(member.getId().toString())
                .claim("name",member.getMemberName())
                .claim("auth",member.getUserRole().toString())
                (생략)
                .compact();
```
과 같은 형태로 생성됩니다.
따라서 이름 또는 권한을 꺼내시려면
claim.get("name")또는claim.get("auth").toString 을 사용하시면 됩니다.

**Comment by ss990321** [comment]
감사합니다~!

**Comment by ss990321** [comment]
문제 해결~!
