### ISSUE TITLE
수정요청 Memo기능 오류수정

### ISSUE THREAD

**Issue by Minwooooooo** [Minwooooooo/FinalProject#20]
현재 :  POST 방식으로 신규 등록 , PUT 방식으로 수정 내용을 받음
문제점 : 이럴경우 FE에서 POST와 PUT을 선택해야 하는데 채팅방 재접속시 오류가 발생

Re : "POST로 통일 / Entity 조회 후 존재할시 수정, 없을시 생성 하는 방식"은 어떠신가요??

**Comment by ss990321** [comment]
POST로 통일 좋습니다. 수정하겠습니다~ 그럼 수정기능과 생성기능을 합치는게 되는건가요?

**Comment by Minwooooooo** [comment]
네 맞습니다. 수정내용 확인했습니다:+1::+1::+1:
