### ISSUE TITLE
ADD Domain) Follower

### ISSUE THREAD

**Issue by dongsub-joung** [Minwooooooo/FinalProject#29]
```java
@Id
@GeneratedValue(strategy = GenerationType.IDENTITY)
private Long id;

@OneToOne
private Member member
    
@Column
private Long followingMemberId

```

작동 방식은 findAllByMember로 해당 유저의 팔로워를 가져와서 로그인 된 사람 id(프론트에서 보내줘야함) 를 이용해 해당 유저를 추가하거나 삭제하는 알고리즘입니다.

**Comment by dongsub-joung** [comment]
#28 에 머지했습니다.

**Comment by dongsub-joung** [comment]
구현이 생각보다 어려워서 테스트를 해보아야 작동하는지 알 것 같습니다.(자신 없음)

**Comment by Minwooooooo** [comment]
현재 방 접속인원 출력 테스트 진행중인데 WebSocket 기반이라 이제야 끝나갑니다
내일 쯤 완료되면 해당 Branch 테스트 진행하겠습니다
수고하셨습니다👍 👍 👍
