### ISSUE TITLE
Err Login 오류

### ISSUE THREAD

**Issue by Minwooooooo** [Minwooooooo/FinalProject#7]
1. Jwt 토큰 생성 오류
  - 알고리즘 설정시 오류(미설정시 "alg": "none")
2.  이름의 형태가 "이름" 으로 저장중

**Comment by Minwooooooo** [comment]
1. Gradle에 이중으로 의존성이 추가된 Jwt 라이브러리 정리
2. 이름 및 프로필사진 substring(1,n-1)을 사용하여 ""제거

**Comment by dongsub-joung** [comment]
> 1. Gradle에 이중으로 의존성이 추가된 Jwt 라이브러리 정리
> 
>     2. 이름 및 프로필사진 substring(1,n-1)을 사용하여 ""제거

대단하십니다.. 이걸 라이브러리를 까봐서 고치시다니..
