### ISSUE TITLE
kakao 로그인 프로필 사진 변경 이슈

### ISSUE THREAD

**Issue by ss990321** [Minwooooooo/FinalProject#9]
1. 카카오 프로필 사진이 회원 프로필 사진으로 고정 
    - 카카오톡 프로필 사진이 변경되면 회원 프로필 사진도 변경되게 해야 함.

**Comment by dongsub-joung** [comment]
로그인 세션을 짧게 해서 새로 로그인할 때마다 사진을 가져오면 해결되지 않을까요?

**Comment by ss990321** [comment]
기능 만들었습니다. 정상적으로 작동할지는 모르겠습니다. 확인 필요합니다.
